# Generated by Django 4.0.4 on 2023-02-23 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_jobcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Job categories'},
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Job title')),
                ('description', models.TextField(max_length=1000, verbose_name='Job description')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum salary')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum salary')),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Experience (in years)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.jobcategory', verbose_name='Job category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.city_data', verbose_name='Job location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider_names')),
            ],
            options={
                'verbose_name': 'Job posting',
                'verbose_name_plural': 'Job postings',
                'ordering': ['-created_at'],
            },
        ),
    ]
