# Generated by Django 4.1.7 on 2023-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_alter_jobcategory_options_postjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='skills_required',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Required Skills'),
        ),
    ]
