# Generated by Django 4.1.7 on 2023-03-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_postjob_skills_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='description',
            field=models.TextField(verbose_name='Job description'),
        ),
    ]
