# Generated by Django 4.1.7 on 2023-03-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_alter_postjob_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='skills_required',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Required Skills'),
        ),
    ]
