# Generated by Django 4.1.7 on 2023-02-21 11:47

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('issuing_org', models.CharField(max_length=50)),
                ('issue_month', models.CharField(choices=[('Month', 'Month'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Month', max_length=50)),
                ('issue_year', models.CharField(choices=[('Year', 'Year'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014')], default='Year', max_length=50)),
                ('expiry_month', models.CharField(choices=[('Month', 'Month'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Month', max_length=50)),
                ('expiry_year', models.CharField(choices=[('Year', 'Year'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014')], default='Year', max_length=50)),
                ('credential_id', models.CharField(max_length=100)),
                ('credential_url', models.URLField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names')),
            ],
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_month', models.CharField(choices=[('Month', 'Month'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Month', max_length=50)),
                ('start_year', models.CharField(choices=[('Year', 'Year'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014')], default='Year', max_length=50)),
                ('end_month', models.CharField(choices=[('Month', 'Month'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Month', max_length=50)),
                ('end_year', models.CharField(choices=[('Year', 'Year'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014')], default='Year', max_length=50)),
                ('url', models.URLField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Docs/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50)),
                ('profile_url', models.URLField(max_length=100)),
                ('profile_des', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names')),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='education',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='seeker_profile_model',
            name='education',
        ),
        migrations.RemoveField(
            model_name='seeker_profile_model',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='seeker_profile_model',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='seeker_profile_model',
            name='skills',
        ),
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(choices=[('Select Course', 'Select Course'), ('BCA', 'BCA'), ('BCOM', 'BCOM'), ('BSC', 'BSC'), ('B-ARCH', 'B-ARCH'), ('BE', 'BE'), ('BTECH', 'BTECH'), ('BBA', 'BBA'), ('BA', 'BA'), ('BMM', 'BMM')], default='Select Course', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='course_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Distance Learning', 'Distance Learning')], default='Full-Time', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='education',
            field=models.CharField(choices=[('Select Education', 'Select Education'), ('10th', '10th'), ('12th', '12th'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], default='Select Education', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='passing_year',
            field=models.CharField(choices=[('Select Passing Year', 'Select Passing Year'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], default='Select Passing Year', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(choices=[('Select Specialization', 'Select Specialization'), ('Computer Science', 'Computer Science'), ('Computer Science Engineering', 'Computer Science Engineering'), ('Web Development', 'Web Development'), ('Android Development', 'Android Development'), ('IOS Development', 'IOS Development'), ('Human Resource', 'Human Resource')], default='Select Specialization', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(choices=[('Select University', 'Select University'), ('Gujarat University', 'Gujarat University'), ('LPU', 'LPU'), ('Other', 'Other')], default='Select University', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names'),
        ),
        migrations.AlterField(
            model_name='seeker_profile_model',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/seeker_profile/avatar.jpeg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[450, 450], upload_to='seeker_profile/'),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
