# Generated by Django 4.0.4 on 2023-02-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_certificate_headline_project_resume_social_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Javascipt', 'Javascript'), ('Bootstrap', 'Bootstrap'), ('ReactJS', 'ReactJS'), ('AngularJS', 'AngularJS'), ('VueJS', 'VueJS'), ('C language', 'C language'), ('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('Web Design', 'Web Design'), ('Photoshop', 'Photoshop'), ('Django', 'Django')], default='C++', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_names')),
            ],
        ),
    ]
