# Generated by Django 4.0.4 on 2023-03-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
