# Generated by Django 4.0.4 on 2023-03-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0005_alter_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='seeker.applyjob')),
            ],
            options={
                'verbose_name': 'Schedule Meeting',
                'verbose_name_plural': 'Schedule Meetings',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
