# Generated by Django 4.0.4 on 2023-03-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0006_schedulemeeting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulemeeting',
            unique_together={('application',)},
        ),
    ]
