# Generated by Django 4.1.7 on 2023-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0011_alter_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemeeting',
            name='location',
            field=models.CharField(max_length=10000, verbose_name='Location'),
        ),
    ]
